[project]
name = "odoo-addons-oca-calendar"
version = "17.0.20250131.0"
dependencies = [
    "odoo-addon-resource_booking>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
